WEBCAM_IDX = 1

IMAGE_WIDTH = 1920
IMAGE_HEIGHT = 1080

AREAS_COUNT = 10
CONTOUR_SIMPLIFY_FACTOR = 3

CONFIDENCE_DETECTION_MIN = 0.5
OSC_RUN = True
OSC_ADDRESS = '127.0.0.1'
OSC_PORT = 7000
OSC_FPS = 30
NUMBERPOOLSIZE = 3
WITH_SHARED_MEM = True
SHARED_MEM_PIPENAME = '/tmp/shared_memory_pipe'
PRINT_DEBUG = False


WITH_WARP_TRANSFORM = False

SHOWCV = True
WITH_POSE= True
WITH_SEGMENTATION = False
