# Example configuration settings
#important settings
IMAGE_WIDTH = 1920
IMAGE_HEIGHT = 1080
AREAS_COUNT = 24
WEBCAM_IDX = 0
SHOWCV = True
CONFIDENCE_DETECTION_MIN = 0.5

OSC_RUN = True
OSC_ADDRESS = "127.0.0.1"
OSC_PORT = 7000
OSC_FPS = 30


NUMBERPOOLSIZE = 3

WITH_SHARED_MEM = True
SHARED_MEM_PIPENAME ='/tmp/shared_memory_pipe1'
